### ISSUE TITLE
doesn't seem to work with node (Promises)

### ISSUE THREAD

**Issue by mcepl** [gaye/dav#78]
I don't know if I do something wrong, but with this example script (the server is Radicale running on the localhost, of course):
```js
'use strict';

var Promise = require('es6-promise').Promise;
var dav = require('dav');

var xhr = new dav.transport.Basic(
    new dav.Credentials({
      username: 'matej'
    })
);

dav.createAccount({
    server: 'http://localhost:5232/matej/contacts.vcf',
    xhr: xhr,
    accountType: 'carddav'
})
.then(function(account) {
  account.addressBooks.forEach(function(addressBook){
    console.log('Found addressbook name ' + addressBook.displayName);
  })
});
```
(and dav version `~1.7.0` installed via npm) I get this:
```
matej@mitmanek: jsContactsSync$ node listcontacts.js 

/home/matej/archiv/2015/projekty/jsContactsSync/node_modules/dav/lib/index.js:2
import debug from 'debug';
^^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/matej/archiv/2015/projekty/jsContactsSync/listcontacts.js:4:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
matej@mitmanek: jsContactsSync$ 
```
This is my `packages.json`:
```js
{
  "name": "jsContactsSync",
  "version": "0.0.0",
  "description": "Synchronize Firefox OS Contacts with the remote CardDAV server.",
  "main": "listcontacts.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "address book",
    "vcard",
    "sync",
    "fxos",
    "carddav",
    "rfc 4791",
    "rfc 6352",
    "rfc 6578",
    "contacts"
  ],
  "author": "Matěj Cepl <mcepl@cepl.eu>",
  "license": "GPLv3",
  "dependencies": {
    "dav": "~1.7.0",
    "es6-promise": "~2.1.0"
  }
}
```
(I had to add `es6-promise`, because otherwise my script crashed on the lack of Promises implementation; BTW, I have node `v0.10.36`).

**Comment by gaye** [comment]
@mcepl Your issue should be solved in dav@1.7.2. Please let me know if you have any other issues!
