### ISSUE TITLE
Failing testsuite

### ISSUE THREAD

**Issue by mcepl** [gaye/dav#80]
With f8be6e7 I get the following on running `make test`:
```
  accounts
    #create
      1) caldav
      2) carddav
      3) without loading collections
      4) without loading objects

  calendars
    5) "before each" hook: callee$1$0

  contacts
    6) "before each" hook: callee$1$0


  0 passing (3s)
  6 failing

  1) accounts #create caldav:
     Error: Bad status: 500
      at [object Object].request.onreadystatechange (/home/matej/archiv/knihovna/repos/dav/lib/xmlhttprequest.js:83:25)
      at [object Object].dispatchEvent (/home/matej/archiv/knihovna/repos/dav/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:570:25)
      at setState (/home/matej/archiv/knihovna/repos/dav/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:589:14)
      at IncomingMessage.<anonymous> (/home/matej/archiv/knihovna/repos/dav/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:427:13)
      at IncomingMessage.emit (events.js:117:20)
      at _stream_readable.js:944:16
      at process._tickCallback (node.js:442:13)

  2) accounts #create carddav:
     Error: Bad status: 500
      at [object Object].request.onreadystatechange (/home/matej/archiv/knihovna/repos/dav/lib/xmlhttprequest.js:83:25)
      at [object Object].dispatchEvent (/home/matej/archiv/knihovna/repos/dav/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:570:25)
      at setState (/home/matej/archiv/knihovna/repos/dav/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:589:14)
      at IncomingMessage.<anonymous> (/home/matej/archiv/knihovna/repos/dav/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:427:13)
      at IncomingMessage.emit (events.js:117:20)
      at _stream_readable.js:944:16
      at process._tickCallback (node.js:442:13)

  3) accounts #create without loading collections:
     Error: Bad status: 500
      at [object Object].request.onreadystatechange (/home/matej/archiv/knihovna/repos/dav/lib/xmlhttprequest.js:83:25)
      at [object Object].dispatchEvent (/home/matej/archiv/knihovna/repos/dav/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:570:25)
      at setState (/home/matej/archiv/knihovna/repos/dav/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:589:14)
      at IncomingMessage.<anonymous> (/home/matej/archiv/knihovna/repos/dav/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:427:13)
      at IncomingMessage.emit (events.js:117:20)
      at _stream_readable.js:944:16
      at process._tickCallback (node.js:442:13)

  4) accounts #create without loading objects:
     Error: Bad status: 500
      at [object Object].request.onreadystatechange (/home/matej/archiv/knihovna/repos/dav/lib/xmlhttprequest.js:83:25)
      at [object Object].dispatchEvent (/home/matej/archiv/knihovna/repos/dav/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:570:25)
      at setState (/home/matej/archiv/knihovna/repos/dav/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:589:14)
      at IncomingMessage.<anonymous> (/home/matej/archiv/knihovna/repos/dav/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:427:13)
      at IncomingMessage.emit (events.js:117:20)
      at _stream_readable.js:944:16
      at process._tickCallback (node.js:442:13)

  5) calendars "before each" hook: callee$1$0:
     Error: Bad status: 500
      at [object Object].request.onreadystatechange (/home/matej/archiv/knihovna/repos/dav/lib/xmlhttprequest.js:83:25)
      at [object Object].dispatchEvent (/home/matej/archiv/knihovna/repos/dav/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:570:25)
      at setState (/home/matej/archiv/knihovna/repos/dav/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:589:14)
      at IncomingMessage.<anonymous> (/home/matej/archiv/knihovna/repos/dav/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:427:13)
      at IncomingMessage.emit (events.js:117:20)
      at _stream_readable.js:944:16
      at process._tickCallback (node.js:442:13)

  6) contacts "before each" hook: callee$1$0:
     Error: Bad status: 500
      at [object Object].request.onreadystatechange (/home/matej/archiv/knihovna/repos/dav/lib/xmlhttprequest.js:83:25)
      at [object Object].dispatchEvent (/home/matej/archiv/knihovna/repos/dav/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:570:25)
      at setState (/home/matej/archiv/knihovna/repos/dav/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:589:14)
      at IncomingMessage.<anonymous> (/home/matej/archiv/knihovna/repos/dav/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:427:13)
      at IncomingMessage.emit (events.js:117:20)
      at _stream_readable.js:944:16
      at process._tickCallback (node.js:442:13)



make: *** [test-integration] Error 6
```

**Comment by gaye** [comment]
Hrm I will take a look. Do the tests pass for you earlier than f8be6e7?

**Comment by mcepl** [comment]
> Hrm I will take a look. Do the tests pass for you earlier than f8be6e7?

I have tried tags `v1.7.2`, `v1.7.0`, `v1.6.5`, `v1.6.4`, and `1.0.0` … all of them failed with at least six errors (`1.0.0` with more).

**Comment by gaye** [comment]
This is what I get when I run the tests and also what I see on ci https://gist.github.com/gaye/4f1e3c7f106c1d1f700d. The integration tests run SabreDAV which is a php caldav server that needs the `php5`, `sqlite3`, and `php5-sqlite` packages installed if you're on Linux. Should get that added to the `README` or perhaps the `Makefile` for when people try to run integration tests.

**Comment by gaye** [comment]
Going to close for now since tests are working for me and on ci.
