### ISSUE TITLE
Promise is not defined

### ISSUE THREAD

**Issue by pwldp** [gaye/dav#89]
Hi,
When I run example on node I got an error:
```
/home/appuser/node_modules/dav/dav.js:4865
  return new Promise(function(resolve, reject) {
             ^
ReferenceError: Promise is not defined
    at Object.co (/home/appuser/node_modules/dav/dav.js:4865:14)
    at Object.createPromise (/home/appuser/node_modules/dav/dav.js:4846:15)
    at Object.<anonymous> (/home/appuser/dav_tests/caldav_test.js:10:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

Node version is 0.10.37

What should I install to run the script?

**Comment by gaye** [comment]
You'll need a version of node with built-in promises. dav's tests run on iojs v1.8.1 but node 0.11 or 0.12 probably works too.

**Comment by pwldp** [comment]
After update to node v 0.12 error has gone.
Thanks.
